### ISSUE TITLE
Research counterparty

### ISSUE THREAD

**Issue by whoabuddy** [bitcoin-nfts/bitcoin-colors#9]
It'd be nice to know more about the end-to-end experience with counterparty in relation to what we're doing.

**Comment by whoabuddy** [comment]
Tagging @loon3 from the working group charter to help with this - specifically want to learn more about the UX and what steps a user must take, e.g. does it require a special wallet? How are states confirmed and displayed?

**Comment by loon3** [comment]
Interacting with counterparty requires a bitcoin wallet that is "counterparty aware", meaning specifically that it reads and displays asset balances from counterparty-lib and has the ability to construct on-chain bitcoin txs with counterparty message data most commonly stored in an op_return output.  

The biggest difference between counterparty and colored utxo based asset systems like RGB is that ALL counterparty data is stored on-chain so wallet software doesn't need to store or share any off-chain information when transacting.  This means that you can receive assets to any bitcoin wallet (even if its not counterparty aware).  You would only need to import your private key to a counterparty aware wallet to construct counterparty specific transactions.  

Since all counterparty messages are stored on-chain, counterparty-lib state is updated every bitcoin block
